config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index'
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movement.rb
# frozen_string_literal: true

class Movement < ApplicationRecord
  # Relations
  belongs_to :product

  MovementTypes = { add: 0, remove: 1 }.freeze
  # Validations
  validates :quantify, presence: true, numericality: true

  def self.get_movement_types
    {
      'Agregar' => MovementTypes[:add],
      'Quitar' => MovementTypes[:remove]
    }
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true
  validates :reference, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_movement
    @product = Product.find(params[:id])
    @movement = Movement.new
  end

  def movement_params
    params.require(:movement).permit(:quantify, :movement_type, :comment)
  end

  def create_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(movement_params)
    @movement.product_id = @product.id

    if @movement.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el movimiento.'
      render :new_movement, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :reference, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= render 'shared/head' %>

  </head>

  <%# Sidebar %> 
  <%= render 'shared/sidebar' %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

   <div class="form-group">
    <%= form.label :reference, style: "display: block" %>
    <%= form.text_field :reference, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control"%>
  </div>

  <div>
    <%= form.submit "Enviar",class:"btn btn-primary" %>
  </div>
<% end %>


    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= product.reference %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Ver detalle del producto", @product, class:"btn btn-primary"%> |
  <%= link_to "Regresar al listado de productos", products_path, class:"btn btn-warning"%>
</div>

app/views/products/index.html.erb
<h1>Lista de productos</h1>
<a href="<%= new_product_path %>" class="btn btn-primary  btn-icon-split"> 
  <span class="icon text-with-50">
    <i class="fa fa-flag"></i>
  </span>
  <span class="text">Crear Producto </span>
</a>
<br>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nombre</th>
      <th>Referencia</th>
      <th>Cantidad</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <%= product.id %> </td>
        <td> <%= product.name %> </td>
        <td> <%= product.reference %> </td>
        <td> <%= 0 %> </td>
        <td> <%= link_to "Detalles", product_path(product), class:"btn btn-primary" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Crear nuevo producto</h1>
<%= link_to "Regresar al listado de productos", products_path, class: "btn btn-primary" %>
<br> </br>
<%= render "form", product: @product %>

app/views/products/new_movement.html.erb
<h1>Crear movimiento</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <table class="table">
        <tr>
           <td><b> Nombre:</b></td>
           <td><%= @product.name %></td>
         </tr>
         <tr>
           <td><b> Referencia:</b></td>
           <td><%= @product.reference %></td>
        </tr>
      </table>

    </div>
  </div>
</div>

<class="row">
     <div class="col-lg-12">
        <div class="card p-5">
            <%= form_with model: @movement, url:create_movement_product_path(@product) do |f|%>

            <% if @movement.errors.any? %>
              < div class="alert alert-danger">
                <h3> <%= flash[:notice] %> </h3>
                <ul>
                <% @movement.errors.full_messages.each do |message|%>
                  <li> <%=message%> </li>
                  <% end %>
                </ul>
              </div>
              <% end %>

              <div class="form-group">
              <%=f.label:movement_type, "Tipo de movimiento" %>
              <%=f.select:movement_type, options_for_select(Movement.get_movement_types), {}, {class: 'form-control'}%>

              <div class="form-group">
              <%= f.label:quantify,"cantidad" %>
              <%= f.number_field :quantify, {class: 'form-control'}%>
              </div>

              <div class="form-group">
              <%= f.label:comment,"comentario" %>
              <%= f.text_area :comment, class: 'form-control'%>
              </div>

              <div class="form-group">
              <%= f.submit 'Crear movimiento', class: 'btn btn-primary'%>
              <%= link_to 'Cancelar', product_path(@product), class: 'btn btn-danger' %>
              </div>


            <% end %>
          </div>
      </div> 
</div>
         

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
     <h1>Detalles del producto</h1>
     <%= link_to "Regresar al listado de productos", products_path, class:'btn btn-primary'%>
     <%= link_to "Editar este producto",edit_product_path(@product), class:'btn btn-primary'%>
     <%= button_to "Eliminar este producto",@product ,method: :delete,  class: 'btn btn-danger'%>
     <%=link_to "Crear movimiento",new_movement_product_path(@product), class:'btn btn-success' %>
  
     <div class="card">
       <table class="table">
         <tr>
           <td><b>Nombre del producto:</b></td>
           <td><%=@product.name %></td>
         </tr>
        <tr>
         <td><b>Referencia:</b></td>
         <td><%=@product.reference%></td>
        </tr>
        <tr>
         <td><b>Descripcion:</b></td>
         <td><%=@product.description%></td>
       </tr>
       <tr>
       <td><b>Cantidad actual:</b></td>
       <td><%= 0 %></td>
       </tr>
       <tr>
         <td><b>Fecha de creacion:</b></td>
         <td><%=@product.created_at%></td>
       </tr>
     </table>
     <div>



  </div>
</div>


 

app/views/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Footer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<!-- Custom fonts for this template-->    
<link
  href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
  rel="stylesheet">
<!-- Custom styles for this template-->
<!-- Bootstrap core JavaScript-->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="js/sb-admin-2.min.js"></script>

app/views/shared/_sidebar.html.erb
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= products_path %>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Productos</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider">



      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>



        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">

      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                                                       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>